// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: worker_service.proto

#include "worker_service.pb.h"
#include "worker_service.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace tensorflow {
namespace grpc {

static const char* WorkerService_method_names[] = {
  "/tensorflow.grpc.WorkerService/RecvTensor",
};

std::unique_ptr< WorkerService::Stub> WorkerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< WorkerService::Stub> stub(new WorkerService::Stub(channel));
  return stub;
}

WorkerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RecvTensor_(WorkerService_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerService::Stub::RecvTensor(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::tensorflow::RecvTensorResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_RecvTensor_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::tensorflow::RecvTensorResponse>* WorkerService::Stub::AsyncRecvTensorRaw(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::tensorflow::RecvTensorResponse>(channel_.get(), cq, rpcmethod_RecvTensor_, context, request);
}

WorkerService::Service::Service() {
  AddMethod(new ::grpc::RpcServiceMethod(
      WorkerService_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< WorkerService::Service, ::tensorflow::RecvTensorRequest, ::tensorflow::RecvTensorResponse>(
          std::mem_fn(&WorkerService::Service::RecvTensor), this)));
}

WorkerService::Service::~Service() {
}

::grpc::Status WorkerService::Service::RecvTensor(::grpc::ServerContext* context, const ::tensorflow::RecvTensorRequest* request, ::tensorflow::RecvTensorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace tensorflow
}  // namespace grpc

