// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: worker_service.proto
// Original file comments:
// Copyright 2016 The TensorFlow Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ==============================================================================
//
#ifndef GRPC_worker_5fservice_2eproto__INCLUDED
#define GRPC_worker_5fservice_2eproto__INCLUDED

#include "worker_service.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tensorflow {
namespace grpc {

// //////////////////////////////////////////////////////////////////////////////
//
// WorkerService defines a TensorFlow service that executes dataflow
// graphs on a set of local devices, on behalf of a MasterService.
//
// A worker service keeps track of multiple "registered graphs". Each
// registered graph is a subgraph of a client's graph, corresponding to
// only the nodes that should execute on this worker (and any
// additional nodes necessary for inter-process communication using
// the `RecvTensor` method).
//
// //////////////////////////////////////////////////////////////////////////////
//
class WorkerService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // See worker.proto for details.
    virtual ::grpc::Status RecvTensor(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::tensorflow::RecvTensorResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::RecvTensorResponse>> AsyncRecvTensor(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::RecvTensorResponse>>(AsyncRecvTensorRaw(context, request, cq));
    }
    // RecvTensor Method
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tensorflow::RecvTensorResponse>* AsyncRecvTensorRaw(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RecvTensor(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::tensorflow::RecvTensorResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::RecvTensorResponse>> AsyncRecvTensor(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tensorflow::RecvTensorResponse>>(AsyncRecvTensorRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::tensorflow::RecvTensorResponse>* AsyncRecvTensorRaw(::grpc::ClientContext* context, const ::tensorflow::RecvTensorRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_RecvTensor_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // See worker.proto for details.
    virtual ::grpc::Status RecvTensor(::grpc::ServerContext* context, const ::tensorflow::RecvTensorRequest* request, ::tensorflow::RecvTensorResponse* response);
    // RecvTensor Method
  };
  template <class BaseClass>
  class WithAsyncMethod_RecvTensor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RecvTensor() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RecvTensor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecvTensor(::grpc::ServerContext* context, const ::tensorflow::RecvTensorRequest* request, ::tensorflow::RecvTensorResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecvTensor(::grpc::ServerContext* context, ::tensorflow::RecvTensorRequest* request, ::grpc::ServerAsyncResponseWriter< ::tensorflow::RecvTensorResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RecvTensor<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_RecvTensor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RecvTensor() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RecvTensor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecvTensor(::grpc::ServerContext* context, const ::tensorflow::RecvTensorRequest* request, ::tensorflow::RecvTensorResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecvTensor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RecvTensor() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::tensorflow::RecvTensorRequest, ::tensorflow::RecvTensorResponse>(std::bind(&WithStreamedUnaryMethod_RecvTensor<BaseClass>::StreamedRecvTensor, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RecvTensor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecvTensor(::grpc::ServerContext* context, const ::tensorflow::RecvTensorRequest* request, ::tensorflow::RecvTensorResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecvTensor(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::tensorflow::RecvTensorRequest,::tensorflow::RecvTensorResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RecvTensor<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RecvTensor<Service > StreamedService;
};

}  // namespace grpc
}  // namespace tensorflow


#endif  // GRPC_worker_5fservice_2eproto__INCLUDED
